baseURL = 'https://dipika.us/'
languageCode = 'en-us'
title = 'Dipika'
theme = 'PaperMod'

[params]
  disableThemeToggle = true
  defaultTheme = "light"

[pagination]
  pagerSize = 6

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "Writing"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 20

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 30
