baseURL = 'https://dipika.us/'
locale = 'en-us'
title = 'Dipika'
theme = 'PaperMod'

[pagination]
  pagerSize = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "Essays"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 20